### ISSUE TITLE
protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by anildigital** [knrz/haikunator#5]
```
iex(1)> Haikunator.build()
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /private/tmp/elixir-20170725-44573-1slglwp/elixir-1.5.0/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /private/tmp/elixir-20170725-44573-1slglwp/elixir-1.5.0/lib/elixir/lib/enum.ex:145: Enumerable.count/1
    (elixir) lib/enum.ex:1709: Enum.random/1
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (haikunator) lib/haikunator.ex:43: Haikunator.build/2
```

I am using Elixir 1.5

**Comment by binarytemple** [comment]
'config' directory was never uploaded to hex.pm
